

services:
  web:
    build: .
    container_name: reco_backend_web
    command: gunicorn reco_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
